// This file is @generated by prost-build.
/// Metadata about the configuration files for jj
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConfigMetadata {
    /// The absolute path to the repo or workspace root.
    /// Access via file_util::path_to/from_bytes
    #[prost(bytes = "vec", tag = "1")]
    pub path: ::prost::alloc::vec::Vec<u8>,
}
